title = "Using arbitrum test network"

[network]
network="arbitrum_rinkeby"

# set only if for custom network
# rpc_endpoint="http://3.236.12.62:8545"

[poll]
MACI_address="0xb150507A3d67c8cdFe89309aE45f9ac57561395e"
poll_processor_and_tallyer_address="0xb239d7BF4920Ed5aE06eCC11793E7D1f3dd4Ed17"
poll_id=0

# Supported params
#   * 10-2-1-2
#   * 10-3-1-2
zkey_params="10-3-1-2"


# [MACI]
# TODO: if commit sha defined, then install maci for that specific commit. default is the HEAD of the `v1` branch
# commit_sha=

# [coordinator]
# TODO: Fail when coordinator doesn't have matching private key
# public_key=
# eth_public_key=

