title = "Using arbitrum test network"

[network]
network="arbitrum_rinkeby"

# set only if for custom network
# rpc_endpoint="http://3.236.12.62:8545"

[poll]
MACI_address="0x0Abd9C6D640f27FbaD4ae4aE39F087f98a11703F"
poll_id=0


# [MACI]
# TODO: if commit sha defined, then install maci for that specific commit. default is the HEAD of the `v1` branch
# commit_sha=

# [coordinator]
# TODO: Fail when coordinator doesn't have matching private key
# public_key=
# eth_public_key=

