title = "Using arbitrum test network"

[network]
network="arbitrum_rinkeby"

# set only if for custom network
# rpc_endpoint="http://3.236.12.62:8545"

[poll]
MACI_address="0xAAf9873558f18a09De055fD16602Aa1e9EB3F6e8"
poll_processor_and_tallyer_address="0x887b8c132A4fE2Ed18e7e8718d2cAA4dE526BE3f"
poll_id=0
zkey_params="10-2-1-2"


# [MACI]
# TODO: if commit sha defined, then install maci for that specific commit. default is the HEAD of the `v1` branch
# commit_sha=

# [coordinator]
# TODO: Fail when coordinator doesn't have matching private key
# public_key=
# eth_public_key=

