[book]
authors = ["Koh Wei Jie"]
language = "en"
multilingual = false
src = "docs"
title = "Minimum Anti-Collusion Infrastructure"

[build]
build-dir = "publish"

[output.html]
mathjax-support = true
