name: Coordinator Service

on:
  push: 
    paths:
      - 'input/**.toml'

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  COORDINATOR_PRIVATE_KEY: ${{ secrets.COORDINATOR_PRIVATE_KEY }}
  ETH_SK: ${{ secrets.ETH_SK }}


jobs:

  generate-proof:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Initialize Project
        run: npm install

      - name: Download rapidsnark (1c137)
        run: |
          mkdir -p ~/rapidsnark/build
          wget -O ~/rapidsnark/build/prover https://maci-devops-zkeys.s3.ap-northeast-2.amazonaws.com/rapidsnark-linux-amd64-1c137
          chmod +x ~/rapidsnark/build/prover

      - name: Download zkeys
        run: |
          wget -qO zkeys.tar.gz https://maci-devops.s3.ap-northeast-2.amazonaws.com/zkeys_glibc-211.tar.gz
          tar -xzvf zkeys.tar.gz

      - name: Generate Proofs
        run: |

          eval `./setEnv.js`


          npx qaci-cli mergeMessages --contract "$MACI_ADDRESS" --poll-id "$POLL_ID"

          npx qaci-cli mergeSignups -x "$MACI_ADDRESS" -o "$POLL_ID"

          npx qaci-cli genProofs -x "$MACI_ADDRESS" \
              -sk macisk."$COORDINATOR_PRIVATE_KEY" \
              -o "$POLL_ID" \
              -r ~/rapidsnark/build/prover \
              -wp ./zkeys/ProcessMessages_10-2-1-2_test \
              -wt ./zkeys/TallyVotes_10-1-2_test \
              -zp ./zkeys/ProcessMessages_10-2-1-2_test.0.zkey \
              -zt ./zkeys/TallyVotes_10-1-2_test.0.zkey \
              -t tally.json \
              -f proofs/

          ls proofs

          cat tally.json
            

      - name: Tar files
        run: tar -cvzf proofs.tar.gz proofs tally.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: proofs
          path: proofs.tar.gz