name: Coordinator Service

on:
  push: 
    # paths:
    #   - 'input/trigger.toml'

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}


jobs:

  create_instance:
    name: Create EC2 instance
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: npm install

      - uses: pulumi/actions@v4
        with:
          command: up
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}


      - name: Get output
        run: |
          echo  $(pulumi stack output publicIp)
          echo  $(pulumi stack output instanceId)
          
          echo "builder_ip=$(pulumi stack output publicIp)" >> $GITHUB_ENV
          echo "instance_id=$(pulumi stack output instanceId)" >> $GITHUB_ENV



  # generate-proof:
  #   needs: create_instance
  #   runs-on: ubuntu-20.04

  #   steps:

      # Make sure the @v0.7.0 matches the current version of the action
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: |
          until [ $(cat result | grep i) ]
          do
            aws ec2 describe-instance-status \
              --instance-ids ${{ env.instance_id }} \
              --filters Name=instance-status.reachability,Values=passed \
              --filters Name=system-status.reachability,Values=passed \
              --query "InstanceStatuses[*].InstanceId" \
              --output text > result
          done
          
          echo "instance created"
          cat result



      - name: OS tweak
        run: ssh ubuntu@${{ env.builder_ip }} -o StrictHostKeychecking=no "bash -s" < ./tweak.sh

      - name: prepare build
        run: ssh ubuntu@${{ env.builder_ip }} -o StrictHostKeychecking=no "bash -s" < ./prepare_build.sh

      - name: run build
        run: ssh ubuntu@${{ env.builder_ip }} -o StrictHostKeychecking=no "bash -s" < ./build.sh


  tear-down:
    if: ${{ always() }}
    # needs: generate-proof
    # needs: create_instance
    runs-on: ubuntu-22.04

    steps:
      - uses: pulumi/actions@v4
        with:
          command: down
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}