name: Coordinator Service

on:
  push: 
    # paths:
    #   - 'input/trigger.toml'

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}


jobs:

  create_instance:
    name: Create EC2 instance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          node-version-file: package.json

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: npm install

      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: gurrpi/pulumi-trial
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  generate-proof:
    runs-on: ubuntu-20.04

    steps:


      - name: bootstrap
        run: ssh@remote ./bootstrap.sh maci_version

      - name: run build
        run: ssh@remote ./build.sh circuit

      - name: Upload Artifact
        run: ssh@remote ./upload.sh