name: Coordinator Service

on:
  push: 
    # paths:
    #   - 'input/**.toml'

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  COORDINATOR_PRIVATE_KEY: ${{ secrets.COORDINATOR_PRIVATE_KEY }}
  ETH_PRIVATE_KEY: ${{ secrets.ETH_SK }}
  ALCHEMY_GOERLI_API_KEY: ${{ secrets.ALCHEMY_GOERLI_API_KEY }}
  ALCHEMY_ARBITRUM_RINKEBY_API_KEY: ${{ secrets.ALCHEMY_ARBITRUM_RINKEBY_API_KEY }}


jobs:

  generate-proof:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Checkout MACI repo
        uses: actions/checkout@v3
        with:
          repository: appliedzkp/maci
          ref: v1
          path: maci

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
        
      - name: Install MACI
        run: ./scripts/install_maci.sh

      - name: Generate Proofs
        run: ./scripts/generate_proofs.sh
            
      - name: Tar files
        run: cd maci/cli && tar -cvzf proofs.tar.gz proofs tally.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: proofs
          path: maci/cli/proofs.tar.gz