name: Core

on:
  push:
  pull_request:
    branches: [ v1 ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v3
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - run: npm install
        working-directory: core

      - run: npm run build
        working-directory: core

      - name: Test
        run: npm run test
        working-directory: core