name: Crypto

on:
  push:
  pull_request:
    branches: [ v1 ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14, 16]

    steps:
      - uses: actions/checkout@v3
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - run: |
          git config --global url."https://github.com/".insteadOf git://github.com/
          npm install
        working-directory: crypto

      - run: npm run build
        working-directory: crypto

      - name: Test
        run: npm run test
        working-directory: crypto
