name: Domainobjs

on:
  push:
  pull_request:
    branches: [ v1 ]

defaults:
  run:
    working-directory: domainobjs

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14, 16]

    steps:
      - uses: actions/checkout@v3
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - run: |
          pwd
          npm install

      - run: |
          pwd
          npm run build

      - name: Test
        run: npm run test
