name: Lint

on:
  push:
    branches: [ v1 ]
  pull_request:
    branches: [ v1 ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14, 16]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

          
      - name: Initialize Project
        run: |
          git config --global url."https://github.com/".insteadOf git://github.com/      
          npm install

      - name: Lint
        run: npm run lint
